In [46]:
# 3.1. Rounding Numerical Values
print(round(1.25361,3))

# .5 is rounded to the nearest even digit !!!
print()
print(round(1.5))
print(round(2.5))

print()
print(round(1627731, -2))
print(round(1627650, -2))

# .5 in format is rounded mathematically or cuted !!!
print()
print(format(1.23445, '0.4f'))
print(format(-1.23445, '0.4f'))
print(format(1234.56755, '0.4f')) # obcina !!!

1.254

2
2

1627700
1627600

1.2345
-1.2345
1234.5675


In [19]:
# 3.1.
a = 2.1
b = 4.2
c = a + b
print(c)
print(round(c, 2))

6.300000000000001
6.3


In [33]:
# 3.2. Performing Accurate Decimal Calculations
a = 2.1
b = 4.2
print((a + b) == 6.3)
print()

from decimal import Decimal
a = Decimal('4.2')
b = Decimal('2.1')
print(a + b)
print((a + b) == Decimal('6.3'))

from decimal import localcontext
print()
c = Decimal('1.225')
with localcontext() as ctx:
    ctx.prec = 3
    print(c/1)

False

6.3
True

1.22


In [35]:
# 3.2.

nums = [1.23e+18, 1, -1.23e+18]
print(sum(nums)) # Notice how 1 disappears !!!

import math
print(math.fsum(nums))

0.0
1.0


In [53]:
# 3.3. Formatting Numbers for Output
x = 1234.56755
print(format(x, '0.4f')) # obcina !!!
print(format(x, '>10.1f'))
print(format(x, '<10.1f'))
print(format(x, '^10.1f'))
print(format(x, ','))
print(format(x, '0,.1f'))
format(x, 'e')
format(x, '0.2E')
print('The value is {:0,.2f}'.format(x))
print('%0.2f' % x)
print('%10.1f' % x)
print('%-10.1f' % x)

1234.5675
    1234.6
1234.6    
  1234.6  
1,234.56755
1,234.6
The value is 1,234.57
1234.57
    1234.6
1234.6    


In [52]:
# 3.3
x = 1234.56789
swap_separators = { ord('.'):',', ord(','):'.' }
print(format(x, ','))
print(format(x, ',').translate(swap_separators))

1,234.56789
1.234,56789
1234.57
    1234.6
1234.6    


In [62]:
# 3.4. Working with Binary, Octal, and Hexadecimal Integers
x = 1234
print(bin(x))
print(format(x, 'b'))
print(oct(x))
print(format(x, 'o'))
print(hex(x))
print(format(x, 'x'))

0b10011010010
10011010010
0o2322
2322
0x4d2
4d2

4294968530
100000000000000000000010011010010
1000004d2


In [64]:
# 3.4.
x = -1234
print(format(x, 'b'))
print(format(x, 'x'))

print(format(2**32 + x, 'b'))
print(format(2**32 + x, 'x'))


-10011010010
-4d2
11111111111111111111101100101110
fffffb2e


In [65]:
# 3.4.
print(int('4d2', 16))
print(int('10011010010', 2))


1234
1234


In [75]:
# 3.5. Packing and Unpacking Large Integers from Bytes
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
print(len(data))
print(int.from_bytes(data, 'little'))
print(int.from_bytes(data, 'big'))
print()
x = 94522842520747284487117727783387188
print(x.to_bytes(16, 'big'))
print(x.to_bytes(16, 'little'))
print()
x = 0x01020304
print(x.to_bytes(4, 'big'))
print(x.to_bytes(4, 'little'))

16
69120565665751139577663547927094891008
94522842520747284487117727783387188

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
b'4\x00#\x00\x01\xef\xcd\x00\xab\x90x\x00V4\x12\x00'

b'\x01\x02\x03\x04'
b'\x04\x03\x02\x01'


In [80]:
# 3.5
import struct
hi, lo = struct.unpack('>QQ', data)
print((hi << 64) + lo)
print()

x = 523 ** 23
print(x)
print(x.bit_length())
nbytes, rem = divmod(x.bit_length(), 8)
if rem:
    nbytes +=1
print(nbytes, rem)
print(x.to_bytes(nbytes, 'little'))

94522842520747284487117727783387188

335381300113661875107536852714019056160355655333978849017944067
208
26 0
b'\x03X\xf1\x82iT\x96\xac\xc7c\x16\xf3\xb9\xcf\x18\xee\xec\x91\xd1\x98\xa2\xc8\xd9R\xb5\xd0'


In [85]:
# 3.6. Performing Complex-Valued Math
a = complex(2, 4)
b = 3 - 5j
print(a,b)
print(a.real)
print(a.imag)
print(a.conjugate())
print(a + b)
print(a * b)
print(a / b)
print(abs(a))

(2+4j) (3-5j)
2.0
4.0
(2-4j)
(5-1j)
(26+2j)
(-0.4117647058823529+0.6470588235294118j)
4.47213595499958


In [86]:
# 3.6.
import cmath
print(cmath.sin(a))
print(cmath.cos(a))
print(cmath.exp(a))

(24.83130584894638-11.356612711218173j)
(-11.36423470640106-24.814651485634183j)
(-4.829809383269385-5.5920560936409816j)


In [89]:
# 3.6.
import cmath
print(cmath.sqrt(-1))

1j


In [98]:
# 3.7. Working with Infinity and NaNs
a = float('inf')
b = float('-inf')
c = float('nan')
print(a,b,c)
print(math.isinf(a))
print(math.isnan(c))
print()

print(a + 45, a * 10, 10 / a)
print(a/a)
print(a + b)
print()

print(c + 23, c * 2, c / 2, math.sqrt(c))

inf -inf nan
True
True

inf inf 0.0
nan
nan

nan nan nan nan


In [100]:
# 3.7
c = float('nan')
d = float('nan')
print(c == d)
print(c is d)

False
False


In [17]:
# 3.8. Calculating with Fractions
from fractions import Fraction
a = Fraction(5, 4)
b = Fraction(7, 16)
print(a, b, a + b)
print()

c = a * b
print(c.numerator)
print(c.denominator)
print(float(c))
print(c.limit_denominator(8), 4/7)
print(c.limit_denominator(14), 6/11)
print()

x = 3.75
y = Fraction(*x.as_integer_ratio())
print(y, 15/4)


5/4 7/16 27/16

35
64
0.546875
4/7 0.5714285714285714
6/11 0.5454545454545454

15/4 3.75


In [1]:
# 3.9. Calculating with Large Numerical Arrays
# Python lists
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
print(x * 2)
print(x + y)
print(x + 10)

[1, 2, 3, 4, 1, 2, 3, 4]
[1, 2, 3, 4, 5, 6, 7, 8]


TypeError: can only concatenate list (not "int") to list

In [2]:
# 3.9.
# Numpy arrays
import numpy as np
ax = np.array([1, 2, 3, 4])
ay = np.array([5, 6, 7, 8])
ax * 2   # array([2, 4, 6, 8])
ax + 10   # array([11, 12, 13, 14])
ax + ay   # array([ 6, 8, 10, 12])

array([ 6,  8, 10, 12])

In [3]:
# 3.9.
#  polynomial
ax = np.array([1, 2, 3, 4])
def f(x):
    return 3*x**2 - 2*x + 7

print(f(ax))   # array([ 8, 15, 28, 47])

# make a two-dimensional grid of 10,000 by 10,000 floats
grid = np.zeros(shape=(10000,10000), dtype=float)

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[1]   # Select row 1: array([5, 6, 7, 8])
a[:,1]   # Select column 1: array([ 2, 6, 10])
a[1:3, 1:3]   # Select a subregion and change it: array([[ 6, 7], [10, 11]])
a[1:3, 1:3] += 10
a + [100, 101, 102, 103]   # Broadcast a row vector across an operation on all rows
np.where(a < 10, a, 10)   # Conditional assignment on an array: 

[ 8 15 28 47]


array([[ 1,  2,  3,  4],
       [ 5, 10, 10,  8],
       [ 9, 10, 10, 10]])