In [3]:
# List comprehensions and readability
# Example 2-1. Build a list of Unicode codepoints from a string.
symbols = '$¢£¥€¤'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))
print(codes)

# Example 2-2. Build a list of Unicode codepoints from a string, take two.
symbols = '$¢£¥€¤'
codes = [ord(symbol) for symbol in symbols]
print(codes)

[36, 162, 163, 165, 8364, 164]
[36, 162, 163, 165, 8364, 164]


In [7]:
# Listcomps no longer leak their variables
x = 'ABC'
dummy = [ord(x) for x in x]
print(x)
print(dummy)

ABC
[65, 66, 67]


In [9]:
# Listcomps versus map and filter
# Example 2-3. The same list built by a listcomp and a map/filter composition.
symbols = '$¢£¥€¤'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]
print(beyond_ascii)
beyond_ascii = list(filter(lambda c: c > 127, map(ord, symbols))) # ???
print(beyond_ascii)

[162, 163, 165, 8364, 164]
[162, 163, 165, 8364, 164]


In [11]:
# Example 2-4. Cartesian product using a list comprehension
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]
print(tshirts)
tshirts = [(color, size) for size in sizes for color in colors ]
print(tshirts)

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
[('black', 'S'), ('white', 'S'), ('black', 'M'), ('white', 'M'), ('black', 'L'), ('white', 'L')]


In [14]:
# Example 2-5. Initializing a tuple and an array from a generator expression
symbols = '$¢£¥€¤'
T = tuple(ord(symbol) for symbol in symbols)
print(T)
import array
I = array.array('I', (ord(symbol) for symbol in symbols))
print(I)

(36, 162, 163, 165, 8364, 164)
array('I', [36, 162, 163, 165, 8364, 164])


In [15]:
# Example 2-6. Cartesian product in a generator expression.
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
for tshirt in ('%s %s' % (c, s) for c in colors for s in sizes):
    print(tshirt)

black S
black M
black L
white S
white M
white L


In [18]:
# Example 2-7. Tuples used as records.
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'),
('ESP', 'XDA205856')]
for passport in sorted(traveler_ids):
    print('%s/%s' % passport)
print()
for country, _ in traveler_ids:
    print(country)

BRA/CE342567
ESP/XDA205856
USA/31195855

USA
BRA
ESP


In [20]:
# example of tuple unpacking with *
print( divmod(20, 8))
t = (20, 8)
print( divmod(*t))

quotient, remainder = divmod(*t)
print(quotient, remainder)

(2, 4)
(2, 4)
2 4


In [23]:
#  Tuple: skiping valuse by unpacking
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename

'idrsa.pub'

In [26]:
# Using * to grab excess items
a, b, *rest = range(5)
print(a, b, rest)
a, b, *rest = range(3)
print(a, b, rest)
a, b, *rest = range(2)
print(a, b, rest)
print()
a, *body, c, d = range(5)
print(a, body, c, d)
*head, b, c, d = range(5)
print(head, b, c, d)

0 1 [2, 3, 4]
0 1 [2]
0 1 []

0 [1, 2] 3 4
[0, 1] 2 3 4


In [67]:
# Example 2-8. Unpacking nested tuples to access the longitude.
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('Sao Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
    ]
print('{:15} |   {:7} | {:^9}'.format('', 'lat.', 'long.'))  # ???
fmt = '{:15} | {:9.4f} | {:9.4f}'
for name, cc, pop, (latitude, longitude) in metro_areas:
    if longitude <= 0:
        print(fmt.format(name, latitude, longitude))
'I have {0} cats and {1} dogs. Dogs: {1}, cats:{0:.^7}!'.format(2,4)

                |   lat.    |   long.  
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
Sao Paulo       |  -23.5478 |  -46.6358


'I have 2 cats and 4 dogs. Dogs: 4, cats:...2...!'

In [13]:
# Example 2-9. Defining and using a named tuple type
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
print('tokyo:', tokyo)
print('tokyo.coordinates:', tokyo.coordinates)

breslau = City('Breslau', 'PL', 1.01, 'missing')
print('breslau:', breslau)
print('breslau.coordinates:', breslau.coordinates)


tokyo: City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))
tokyo.coordinates: (35.689722, 139.691667)
breslau: City(name='Breslau', country='PL', population=1.01, coordinates='missing')
breslau.coordinates: missing


In [15]:
# Example 2-10. Named tuple attributes and methods
print('City._fields', City._fields)
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613889, 77.208889))
delhi = City._make(delhi_data)
print('delhi._asdict:', delhi._asdict())
print('delhi.coordinates:', delhi.coordinates)
print('delhi.coordinates.long:', delhi.coordinates.long)
print()

for key, value in delhi._asdict().items():
    print(key + ':', value)

City._fields ('name', 'country', 'population', 'coordinates')
delhi._asdict: OrderedDict([('name', 'Delhi NCR'), ('country', 'IN'), ('population', 21.935), ('coordinates', LatLong(lat=28.613889, long=77.208889))])
delhi.coordinates: LatLong(lat=28.613889, long=77.208889)
delhi.coordinates.long: 77.208889

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613889, long=77.208889)


In [16]:
# Tuples as immutable lists
print('delhi[0]:', delhi[0])

delhi[0]: Delhi NCR


In [53]:
# Slicing
l = [10, 20, 30, 40, 50, 60]
print('l[:]:', l[:])
print('l[:3]:',l[:3]) # split at 1
print('l[3:]:', l[3:]) # split from 3
print()
print("'bicycle'[::3]:", 'bicycle'[::3])
print("'bicycle'[::-1]:", 'bicycle'[::-1])
print("'bicycle'[::-2]:", 'bicycle'[::-2])

l[:]: [10, 20, 30, 40, 50, 60]
l[:3]: [10, 20, 30]
l[3:]: [40, 50, 60]

'bicycle'[::3]: bye
'bicycle'[::-1]: elcycib
'bicycle'[::-2]: eccb


In [52]:
# Named slices
# Example 2-11. Line items from a flat file invoice
invoice = """
0.....6.................................40..........52.55....
1909  Pimoroni PiBrella                 $17.50      3  $52.50
1489  6mm Tactile Switch x20             $4.95      2   $9.90
1510  Panavise Jr. - PV-201             $28.00      1  $28.00
1601  PiTFT Mini Kit 320x240            $34.95      1  $34.95
"""
SKU = slice(0, 6)
DESCRIPTION = slice(6, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)
line_items = invoice.split('\n')[2:]
for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

$17.50       Pimoroni PiBrella                 
 $4.95       6mm Tactile Switch x20            
$28.00       Panavise Jr. - PV-201             
$34.95       PiTFT Mini Kit 320x240            
 


In [61]:
# Assigning to slices
l = list(range(10))
print(l)
l[2:5] = [20, 30]  # removed 4
print(l)
del l[5:7]
print(l)
l[3::2] = [11, 22]
print(l)
l[2:5] = [100]
print(l)
l[2:5] = 100

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 8, 9]
[0, 1, 20, 11, 5, 22, 9]
[0, 1, 100, 22, 9]


TypeError: can only assign an iterable

In [93]:
# Using + and * with sequences
l = [1, 2, 3]
print('l * 5 =', l * 5)
print("5 * 'abcd' =", 5 * 'abcd')

# Niby źle ale dobrze :) ???
my_list = [[]] * 3
print('my_list =', my_list)
my_list[1]=[1,2]
print('my_list =', my_list)
print('my_list[1][1]) =', my_list[1][1])
my_list[0] = 'abcd'
my_list[2] = 1, 2, 3
print('my_list =', my_list)
print('my_list[0][1]) =', my_list[0][1])

l * 5 = [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
5 * 'abcd' = abcdabcdabcdabcdabcd
my_list = [[], [], []]
my_list = [[], [1, 2], []]
my_list[1][1]) = 2
my_list = ['abcd', [1, 2], (1, 2, 3)]
my_list[0][1]) = b


In [102]:
# Example 2-12. A list with 3 lists of length 3 can represent a Tic-tac-toe board
board = [['_'] * 3 for i in range(3)]
print('board =', board)
board[1][2] = 'X'
print('board =', board)
print()
# kod równoważny:
board = []
for i in range(3):
    row = ['_'] * 3 #
    board.append(row)
print('board =', board)
board[1][2] = 'X'
print('board =', board)

board = [['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
board = [['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

board = [['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
board = [['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]


In [101]:
# Example 2-13. A list with with three references to the same list is useless
weird_board = [['_'] * 3] * 3
print('weird_board =', weird_board)
weird_board[1][2] = 'O'
print('weird_board =', weird_board)
print()
# kod równoważny:
row = ['_'] * 3
weird_board = []
for i in range(3):
    weird_board.append(row)
print('weird_board =', weird_board)
weird_board[1][2] = 'O'
print('weird_board =', weird_board)

weird_board = [['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
weird_board = [['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]

weird_board = [['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
weird_board = [['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]


In [113]:
# Augmented assignment with sequences
l = [1, 2, 3]
print('id(l) =', id(l))
l *= 2
print('l =', l)
print('id(l) =', id(l))
print()
# in unmutable
t = (1, 2, 3)
print('id(t) =', id(t))
t *= 2
print('t =', t)
print('id(t) =', id(t))

id(l) = 140696762277256
l = [1, 2, 3, 1, 2, 3]
id(l) = 140696762277256

id(t) = 140696762340912
t = (1, 2, 3, 1, 2, 3)
id(t) = 140696771506440


In [117]:
# A += assignment puzzler / Example 2-14. A riddle
t = (1, 2, [30, 40])
t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [120]:
# list.sort and the sorted 
fruits = ['grape', 'raspberry', 'apple', 'banana']
print('fruits =',fruits)
print('sorted(fruits) =',sorted(fruits))
print('sorted(fruits, reverse=True) =', sorted(fruits, reverse=True))
print('sorted(fruits, key=len)=', sorted(fruits, key=len))
print('sorted(fruits, key=len, reverse=True) =', sorted(fruits, key=len, reverse=True))
print('fruits =',fruits)
fruits.sort()
print('fruits =',fruits)

fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits) = ['apple', 'banana', 'grape', 'raspberry']
sorted(fruits, reverse=True) = ['raspberry', 'grape', 'banana', 'apple']
sorted(fruits, key=len)= ['grape', 'apple', 'banana', 'raspberry']
sorted(fruits, key=len, reverse=True) = ['raspberry', 'banana', 'grape', 'apple']
fruits = ['grape', 'raspberry', 'apple', 'banana']
fruits = ['apple', 'banana', 'grape', 'raspberry']


In [3]:
# Example 2-17. bisect finds insertion points for items in a sorted sequence
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}'

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)  # <1>
        offset = position * '  |'  # <2>
        print(ROW_FMT.format(needle, position, offset))  # <3>

if __name__ == '__main__':

    if sys.argv[-1] == 'left':    # <4>
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect

    print('DEMO:', bisect_fn.__name__)  # <5>
    print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
    demo(bisect_fn)

DEMO: bisect
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


In [4]:
# Example 2-18. Given a test score, grade returns the corresponding letter grade
def grade(score, breakpoints=[60, 70, 80, 90], grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]
[grade(score) for score in [33, 99, 77, 70, 89, 90, 100]]

['F', 'A', 'C', 'C', 'B', 'A', 'A']

In [9]:
# Example 2-19. Insort keeps a sorted sequence always sorted
import bisect
import random

SIZE = 7
random.seed(1729)
my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


In [1]:
# Example 2-20. Creating, saving and loading a large array of floats.
from array import array
from random import random
floats = array('d', (random() for i in range(10**5)))
print('floats[-1]=', floats[-1])
fp = open('files/floats.bin', 'wb')
floats.tofile(fp)
fp.close()
fp.close()
floats2 = array('d')
fp = open('files/floats.bin', 'rb')
floats2.fromfile(fp, 10**5)
fp.close()
print('floats2[-1]=', floats2[-1])
print('floats2 == floats: ', floats2 == floats)

floats[-1]= 0.1510649258659139
floats2[-1]= 0.1510649258659139
floats2 == floats:  True


In [13]:
# Example 2-21. Changing the value of an array item by poking one of its bytes.
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
print('len(memv) =', len(memv))
print('memv[0] =', memv[0])
print()
memv_oct = memv.cast('B')
print('memv_oct.tolist() =', memv_oct.tolist())
memv_oct[5] = 4
print('numbers =', numbers)

len(memv) = 5
memv[0] = -2

memv_oct.tolist() = [254, 255, 255, 255, 0, 0, 1, 0, 2, 0]
numbers = array('h', [-2, -1, 1024, 1, 2])


In [23]:
# Example 2-22. Basic operations with rows and columns in a numpy.ndarray
import numpy
a = numpy.arange(12)
print('a =', a)
print('type(a) =', type(a))
print('a.shape =', a.shape)
a.shape = 3, 4
print('a:3x4 =\n', a)
print('type(a) =', type(a))
print()
print('a[2] =', a[2])
print('a[2, 1] =', a[2, 1])
print('a[:, 1] =', a[:,1])
print()
print('a.transpose()=\n', a.transpose())

a = [ 0  1  2  3  4  5  6  7  8  9 10 11]
type(a) = <class 'numpy.ndarray'>
a.shape = (12,)
a:3x4 =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
type(a) = <class 'numpy.ndarray'>

a[2] = [ 8  9 10 11]
a[2, 1] = 9
a[:, 1] = [1 5 9]

a.transpose()=
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [6]:
# NumPy loading, saving operations - 1
from array import array
from random import random
import numpy
numpy.savetxt('files/floats_10**5.txt', array('f', (random() for i in range(10**5))))
floats = numpy.loadtxt('files/floats.txt')
print('READY')

READY


In [7]:
# NumPy loading, saving operations - 2
print('floats[-3:]=', floats[-3:])
floats *= .5
print('floats[-3:]=', floats[-3:])

from time import perf_counter as pc
t0 = pc()
floats /= 3
print('czas[s] =', pc() - t0)

floats[-3:]= [ 0.83207315  0.2560527   0.58863461]
floats[-3:]= [ 0.41603658  0.12802635  0.29431731]
czas[s] = 0.0014571260003322095


In [9]:
# NumPy loading, saving operations - 3

t0 = pc()
numpy.save('files/floats_10**5', floats)
print('czas zapisu[s] =', pc() - t0)
t0 = pc()
floats2 = numpy.load('files/floats_10**5.npy', 'r+')
print('czas ladowania[s] =', pc() - t0)
t0 = pc()
floats2 *= 6
print('czas mnozenia[s] =', pc() - t0)
print('floats2[-3:] =',floats2[-3:])

czas zapisu[s] = 0.00886192400002983
czas ladowania[s] = 0.0015038859996820975
czas mnozenia[s] = 0.0006366259999595059
floats2[-3:] = [ 0.83207315  0.2560527   0.58863461]


In [51]:
# Deques and other queues
from collections import deque
dq = deque(range(10), maxlen=10)
print('dq =', dq)
dq.rotate(3)
print('dq =', dq)
dq.rotate(-4)
print('dq =', dq)
dq.extend([11, 22, 33])
print('dq =', dq)
dq.extendleft([10, 20, 30, 40])
print('dq =', dq)

dq = deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
dq = deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)
dq = deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)
dq = deque([4, 5, 6, 7, 8, 9, 0, 11, 22, 33], maxlen=10)
dq = deque([40, 30, 20, 10, 4, 5, 6, 7, 8, 9], maxlen=10)


In [73]:
# list unpacking
mylist = (1,2,3,4,5)
*_, x, y = mylist
print(x,y)

4 5
